// <auto-generated/>

// <copyright company="KapitanH" file="Program.cs">
// (C) 2015 KapitanH 
// </copyright>

namespace PlusPad
{
    using System;
    using System.Windows.Forms;

    public static class Program
    {
        [STAThread]
        public static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Main());
        }
    }
}
