// <auto-generated/>

// <copyright company="KapitanH" file="Win32.cs">
// (C) 2015 KapitanH
// </copyright>

namespace PlusPad
{
    using System.Runtime.InteropServices;
    
    /// <summary>
    /// Grants access to the Windows API.
    /// </summary>
    public class Win32
    {
        #region Keycodes
        /// <summary>
        /// Keycode gehaltene Tase.
        /// </summary>
        public const int KeyEventfExtendedKey = 0x1;

        /// <summary>
        /// Keycode Taste nicht gedrückt.
        /// </summary>
        public const int KeyEventfKeyUp = 0x2;

        /// <summary>
        /// Keycode linke Maustaste gedrückt.
        /// </summary>
        public const int MouseEventfLeftDown = 0x0002;

        /// <summary>
        /// Keycode linke Maustaste nicht gedrückt.
        /// </summary>
        public const int MouseEventfLeftUp = 0x0004;

        /// <summary>
        /// Keycode rechte Maustaste gedrückt.
        /// </summary>
        public const int MouseEventfRightDown = 0x0008;

        /// <summary>
        /// Keycode rechte Maustaste nicht gedrückt.
        /// </summary>
        public const int MouseEventfRightUp = 0x0010;

        /// <summary>
        /// Keycode Mausrad.
        /// </summary>
        public const int MouseEventfWheel = 0x0800;

        /// <summary>
        /// Keycode 0.
        /// </summary>
        public const int K0 = 0x30;

        /// <summary>
        /// Keycode 1.
        /// </summary>
        public const int K1 = 0x31;

        /// <summary>
        /// Keycode 2.
        /// </summary>
        public const int K2 = 0x32;

        /// <summary>
        /// Keycode 3.
        /// </summary>
        public const int K3 = 0x33;

        /// <summary>
        /// Keycode 4.
        /// </summary>
        public const int K4 = 0x34;

        /// <summary>
        /// Keycode 5.
        /// </summary>
        public const int K5 = 0x35;

        /// <summary>
        /// Keycode 6.
        /// </summary>
        public const int K6 = 0x36;

        /// <summary>
        /// Keycode 7.
        /// </summary>
        public const int K7 = 0x37;

        /// <summary>
        /// Keycode 8.
        /// </summary>
        public const int K8 = 0x38;

        /// <summary>
        /// Keycode 9.
        /// </summary>
        public const int K9 = 0x39;

        /// <summary>
        /// Keycode A.
        /// </summary>
        public const int KA = 0x41;

        /// <summary>
        /// Keycode B.
        /// </summary>
        public const int KB = 0x42;

        /// <summary>
        /// Keycode C.
        /// </summary>
        public const int KC = 0x43;

        /// <summary>
        /// Keycode D.
        /// </summary>
        public const int KD = 0x44;

        /// <summary>
        /// Keycode E.
        /// </summary>
        public const int KE = 0x45;

        /// <summary>
        /// Keycode F.
        /// </summary>
        public const int KF = 0x46;

        /// <summary>
        /// Keycode G.
        /// </summary>
        public const int KG = 0x47;

        /// <summary>
        /// Keycode H.
        /// </summary>
        public const int KH = 0x48;

        /// <summary>
        /// Keycode I.
        /// </summary>
        public const int KI = 0x49;

        /// <summary>
        /// Keycode J.
        /// </summary>
        public const int KJ = 0x4A;

        /// <summary>
        /// Keycode K.
        /// </summary>
        public const int KK = 0x4B;

        /// <summary>
        /// Keycode L.
        /// </summary>
        public const int KL = 0x4C;

        /// <summary>
        /// Keycode M.
        /// </summary>
        public const int KM = 0x4D;

        /// <summary>
        /// Keycode N.
        /// </summary>
        public const int KN = 0x4E;

        /// <summary>
        /// Keycode O.
        /// </summary>
        public const int KO = 0x4F;

        /// <summary>
        /// Keycode P.
        /// </summary>
        public const int KP = 0x50;

        /// <summary>
        /// Keycode Q.
        /// </summary>
        public const int KQ = 0x51;

        /// <summary>
        /// Keycode R.
        /// </summary>
        public const int KR = 0x52;

        /// <summary>
        /// Keycode S.
        /// </summary>
        public const int KS = 0x53;

        /// <summary>
        /// Keycode T.
        /// </summary>
        public const int KT = 0x54;

        /// <summary>
        /// Keycode U.
        /// </summary>
        public const int KU = 0x55;

        /// <summary>
        /// Keycode V.
        /// </summary>
        public const int KV = 0x56;

        /// <summary>
        /// Keycode W.
        /// </summary>
        public const int KW = 0x57;

        /// <summary>
        /// Keycode X.
        /// </summary>
        public const int KX = 0x58;

        /// <summary>
        /// Keycode Y.
        /// </summary>
        public const int KY = 0x59;

        /// <summary>
        /// Keycode Z.
        /// </summary>
        public const int KZ = 0x5A;

        /// <summary>
        /// Keycode Pfeiltaste links.
        /// </summary>
        public const int VKLEFT = 0x25;

        /// <summary>
        /// Keycode Pfeiltaste rechts.
        /// </summary>
        public const int VKRIGHT = 0x27;

        /// <summary>
        /// Keycode Shift links.
        /// </summary>
        public const int VKLSHIFT = 0xA0;

        /// <summary>
        /// Keycode Steuerung links.
        /// </summary>
        public const int VKLCONTROL = 0xA2;

        /// <summary>
        /// Keycode Backspace.
        /// </summary>
        public const int VKBACK = 0x08;

        /// <summary>
        /// Keycode Leertaste.
        /// </summary>
        public const int VKSPACE = 0x20;

        /// <summary>
        /// Keycode Komma.
        /// </summary>
        public const int VKOEMCOMMA = 0xBC;

        /// <summary>
        /// Keycode Punkt.
        /// </summary>
        public const int VKOEMPERIOD = 0xBE;

        /// <summary>
        /// Keycode Escape.
        /// </summary>
        public const int VKESCAPE = 0x1B;

        /// <summary>
        /// Keycode F3.
        /// </summary>
        public const int VKF3 = 0x72;

        /// <summary>
        /// Keycode F5.
        /// </summary>
        public const int VKF5 = 0x74;
        #endregion

        /// <summary>
        /// Triggers a keyboard event.
        /// </summary>
        /// <param name="bVk">The key code.</param>
        /// <param name="bScan">The scan code.</param>
        /// <param name="dwFlags">The event type.</param>
        /// <param name="dwExtraInfo">Additional information.</param>
        [DllImport("user32.dll")]
        public static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, uint dwExtraInfo);

        /// <summary>
        /// Triggers a mouse event.
        /// </summary>
        /// <param name="dwFlags">The event type.</param>
        /// <param name="dx">The x-axis position.</param>
        /// <param name="dy">The y-axis position.</param>
        /// <param name="cButtons">The direction of the mouse wheel.</param>
        /// <param name="dwExtraInfo">Additional information.</param>
        [DllImport("user32.dll", CharSet = CharSet.Auto, CallingConvention = CallingConvention.StdCall)]
        public static extern void mouse_event(uint dwFlags, int dx, int dy, int cButtons, uint dwExtraInfo);
    }
}
